M48
; DRILL file {KiCad 7.0.9} date Wed Dec 11 14:01:52 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-12-11T14:01:52+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C4.300
%
G90
G05
T1
X-6.75Y10.5
X-6.75Y-10.5
X6.75Y10.5
X6.75Y-10.5
T2
X-15.25Y15.25
X-15.25Y-15.25
X15.25Y15.25
X15.25Y-15.25
T0
M30
